spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:musinsa
    username: sa

  redis:
    host: localhost
    port: 6380
    max-heap-size: 128M

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: false
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
    open-in-view: false

  sql:
    init:
      mode: always
      encoding: utf-8

  h2:
    console:
      enabled: true

logging.level:
  org:
    hibernate.SQL: debug
